version: 0.0
os: linux
files:
  - source: /index.js
    destination: /var/www/backend/ 
  - source: /package.json
    destination: /var/www/backend/   
  - source: /package-lock.json
    destination: /var/www/backend/    
  - source: /node_modules
    destination: /var/www/backend/node_modules_backend


hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

